### ISSUE TITLE
seller's map: get locations from database rather than google geocoder

### ISSUE THREAD

**Issue by King-Mob** [Code-Operative/Reuse#32]

**Comment by kyeap** [comment]
Since the map is inserted over JS and not a module, we can't get the data directly from the database. We could however use the prestashop webservice to get the data. 

currently I can think of two ways how to get the user input google maps URL from the webservice. 
1) Using the address fields of the BUYER 
2) Creating a new webservice that returns the value in the custom field in seller profile i created. This would take more time. 

Both these methods are documented in postcode module docs.

**Comment by King-Mob** [comment]
getting the following error on calling the api/googleMapUrl

```
Class 'googlemap' not found in
/home/codeoperativeco/public_html/classes/webservice/WebserviceRequest.php:566
Stack trace:
#0 /home/codeoperativeco/public_html/webservice/dispatcher.php(90): WebserviceRequestCore->fetch('2RRCL19N8KPXHW7...',
'GET', 'googleMapUrl', Array, false, NULL)
#1 {main}
thrown in /home/codeoperativeco/public_html/classes/webservice/WebserviceRequest.php on line 566
```

So I'm assuming this means you're halfway there with adding the webservice?

**Comment by kyeap** [comment]
yes, I need to find a way how to add the class properly. The way i tried didn't seem to work. All steps are documented in the postcode module documentation.
