### ISSUE TITLE
Image inside of product tile frame BUG

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#56]

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/117438358-5c2e7300-af29-11eb-9f8c-173849b47c25.png)

Image seems to drop inside of frame?

**Comment by kyeap** [comment]
This isn't a bug, this is because the image you uploaded has white space on top, if you crop it and upload then it should be right. 

[This is your image](https://reuse-home.org.uk/7-home_default/sofa.jpg)

If you crop them properly: 
![image](https://user-images.githubusercontent.com/39419492/117539185-7176d080-b001-11eb-9171-daa3bf01482b.png)

**Comment by MelissaMc20** [comment]
The imae I uploaded is this > 
![alcrossagh-3-seater-sofa](https://user-images.githubusercontent.com/59023121/117655500-0fe46c80-b18f-11eb-93f1-0fad0e7fe811.jpg)

There is no white border, could it be that it's somehow adding one when I upload it?

**Comment by King-Mob** [comment]
The site is adding borders to the images to make them the right shape.
