### ISSUE TITLE
Remove postcode module bug

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#82]
when in debug mode, the check postcode module is giving some errors.

Suspect: the hook is running all the time we might need to restrain when the hook is ran.

**Comment by elalelopez** [comment]
The function executes three times meanwhile de page is render. With a little check, the bug was fixed.

But the function is not working in local (i don't know why yet). It's working in develop server. 

In local is Returning:

POST http://localhost:250/module/postcodecheck/checkpostcode?ajax=1 500 (Internal Server Error)

Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
