### ISSUE TITLE
Create contineous intergration for development server

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#89]

**Comment by kyeap** [comment]
Tried multiple github action with FTP deploy without success, always exit after time limit (360minutes). 

Upload development1 via zip and it seems to work. Files that needs changes: 
- .htaccess (missing in development1) 
- DB settings: App -> config -> parameters.php 

Next step is to find a way to zip and unzip via github action

**Comment by javierginez** [comment]
Hi @kyeap ! How are you?
Given the additional effort needed with some unexpected challenges, and in order to meet the deadlines with the client, we (@renerecalde + @elalelopez ) decided to focus our efforts on the committed functionalities and leave this issue for later. 
Do you agree?

**Comment by kyeap** [comment]
Hi @javierginez, yes definitely. I have already tried deploying without github and it seems to work, so we can continue with that first. When do you think we are able to finish with the functionalities? Should I contact the client and let them know there might be a delay? Is there anything that I can help out with? Thanks!

**Comment by javierginez** [comment]
Hi @kyeap !! Great! 👍 

We are going to have a check-point meeting tomorrow, in order to get a more clear vision on what is pending to do.

Then, I will let you if it's necessary to contact the client or not. @renerecalde and @elalelopez are giving their best to meet the deadlines, so I'm confident we'll deliver all features on time. 💯

**Comment by renerecalde** [comment]
This task has been outside the scope of the project.
